version: "3.8"
services:
  django-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Пробрасываем порт на host-машину
    environment:
      DEBUG: "1"
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: testdb
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - database_network

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: testdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - database_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com # Email для входа в pgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin       # Пароль для входа в pgAdmin
    ports:
      - 8080:80 # Локальный порт 8080 перенаправлен на порт 80 контейнера pgAdmin
    networks:
      - database_network

volumes:
  postgres_data: # Создаем volume для сохранения данных PostgreSQL

networks:
  database_network: # Создаем пользовательскую сеть, в которой будут работать оба контейнера
    driver: bridge

