# Generated by Django 5.1.3 on 2024-11-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_column='username')),
                ('user_surname', models.CharField(db_column='user_surname')),
                ('user_hobby', models.CharField(db_column='hobby')),
            ],
            options={
                'db_table': 'Test_Users',
                'managed': True,
            },
        ),
    ]
